### ISSUE TITLE
Diallelic Autosomal Locus - Missing third parameter waa

### ISSUE THREAD

**Issue by tjkautz** [cbs-rlt/populus#14]
To whom it may concern, 

I am experiencing a problem using this model referenced in the subject box above. In the fitness/ selection coefficient options, under fitness there are two parameters, wAA and wAa. However a waa is needed so I can run my practical for university and I cannot seem to add or change a parameter so that the value of waa can be changed? 
A photo is attached to show what I mean. 
Any help would be greatly appreciated. 

Kind Regards

Abigail Buck 
![image](https://user-images.githubusercontent.com/12702420/33574955-ab45f646-d900-11e7-8203-4916431ca169.png)

**Comment by tjkautz** [comment]
I tried on both 5.5 and 6 and noticed the waa is missing on both versions. I resized my window but it still did not display.

**Comment by larsroe** [comment]
I've put further changes in the main code branch to change to a scrollbar if it gets too small to be sure, but this is essentially the same issue as https://github.com/cbs-rlt/populus/issues/1, so I'll close this one.
