### ISSUE TITLE
Plot lines disappear 

### ISSUE THREAD

**Issue by tjkautz** [cbs-rlt/populus#16]
We received an email with this information:
I have avoided version 6.0 because it seems to have issues. This morning, my students used 6 because 5.5 wasn't available. We used 6 on several different machines w/ Windows 7, 8.1, and 10.  All of them had a problem in the Density-Independent Growth model. After viewing the graph of dN/dtN vs N, then clicking back to any of the other plot types, the plot lines seem to disappear (and do not reappear, even after clicking on the View button) because it fails to autoset the value ranges of the graph axes unless manually prompted to do so.

**Comment by larsroe** [comment]
Fixed in change https://github.com/cbs-rlt/populus/commit/86e51d1e9f2bb573541e35ea60ae9bbce3d5a1ca
