### ISSUE TITLE
problems in the PDF

### ISSUE THREAD

**Issue by carzamora** [cbs-rlt/populus#18]
Hi, I am interested in know if it is possible to upload in GitHub the help file to make some contributions in that file. For example, in page 12, two times is cited de Figure 4.8 but is it not in the file, I think is Fig. 1 but is an error, and in that section above the Figure 1 didn't say Figure 1. I think we can find a lot of mistakes in the file and is important to fix it.

**Comment by larsroe** [comment]
The PDF is generated from a Word file which is not part of this repository. I would recommend sending an email to the Populus team: https://cbs.umn.edu/populus/contact .

Thanks for the feedback, and apologies for the late response on this!
