### ISSUE TITLE
Unable to Run Program on Mac

### ISSUE THREAD

**Issue by kendallpfeiffer** [cbs-rlt/populus#21]
Downloaded the files, unzipped the zip. and have java downloaded and still nothing is running the program. Help.

**Comment by DanielSanRocha** [comment]
Hello @kendallpfeiffer, can you give a more detailed explanation of your problem? Maybe some screenshots or log errors.  Where did you downloaded the zip file?

It would also be nice if you give the exact step to reproduce the error. Also be sure to put your java version and osx version and how you installed java in your machine. I am not an owner of the project but I can try to help.

Sidenote: Make sure you have given your computer permission to execute software from an unindentified developer.

**Comment by larsroe** [comment]
As @DanielSanRocha said, it's probably a permissions error, in which case you'd have to enable Gatekeeper. If you run the application on the Terminal, it should show you better diagnostics.

**Comment by kendallpfeiffer** [comment]
basically everytime i download the zip all that comes up is a folder with a bunch of folders within it and none of the folders have exectuable programs within them? I updated my mac, have the latest version of java dowloaded. This stupid assignment is about to be 10% of my grade and im getting punished for something out of my control. Im losing my mind. please help

**Comment by kendallpfeiffer** [comment]
how do i give my mac permission?

**Comment by DanielSanRocha** [comment]
well, there is a version of populus for mac in the build. I did not find this version for download in the site. If you send me your email I can send attached the executable (instead of a jar) if it is okay with you, this version probably work best with mac.

**Comment by kendallpfeiffer** [comment]
yes that would be so great kdp15d@my.fsu.edu

**Comment by larsroe** [comment]
Also you can try:

Install Java runtime engine if you don't have it already. You just need the JRE. Either go to https://www.java.com/en/download/help/mac_install.html, or you can run "brew cask install java" if you run homebrew.

Get a jar file from https://cbs.umn.edu/populus/download-populus. I downloaded it as "PopulusAll_Jan_2018.jar".

If you click on the JAR file and you get a warning that it doesn't allow it, open "Systems Settings" > "Security & Privacy". If you unlock that, there should be a setting that tells you to allow you to run the program you previously failed to open.

If you can't get the previous step to work, you can also run "java -jar PopulusAll_Jan_2018.jar" from the Terminal.

Sorry about the frustration. This github page is specifically for the source code, and isn't meant to be "consumer friendly". The installer has not kept up with the latest changes.

**Comment by DanielSanRocha** [comment]
I think would be nice to have a place with the Mac bundle available for download in the main page don`t you think @larsroe ?

**Comment by kendallpfeiffer** [comment]
this link just takes me to the link that my professor gave me. I am seriously not a tech-savy person. like I am not a dumbass but my professor really thinks I work for geek squad or something. If I screenrecord my page and show you the issue could that maybe help solve what I am doing wrong?
________________________________

**Comment by larsroe** [comment]
Resolved this offline for the user. I've also recently made changes to the code for an installer. You can now run the following command to create an application package:

./gradlew jpackage
